Repository harrytran103/productivity-apps, pull requests merged in 2022-10, with the labels that each got.

#2 Enhance Readme
  README.md
  by_app.png
  by_country.png
  by_job_position.png
Labels: enhancement, hacktoberfest-accepted

#3 cheer: my productivity apps used
  README.md
Labels: hacktoberfest-accepted

#4 Add my productivity apps
  README.md
Labels: enhancement, hacktoberfest-accepted

#5 Update my productivity apps
  README.md
Labels: enhancement, hacktoberfest-accepted

#6 Update chart
  by_app.png
Labels: enhancement
